Sprint7
ClevertecFrontendLab/AndreyTverdovskiy pull request #6
Opened 2023-03-25 18:48 UTC by AndreyTverdovskiy

2023-03-25 18:58 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 97%.
Общее количество тестов: 98.
Количество непройденных тестов: 2.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/9-app%20-burger-menu-close-768px.png)
***
**Sprint 4 -- search and sort -- bread crumbs -- desktop -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20desktop%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 6 -- booking and book rate -- booking edit modal -- check edit booking request success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679770694/Sprint%206%20--%20booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20edit%20booking%20request%20success%20(failed).png)

2023-03-25 22:21 UTC, ValadzkoAliaksei commented on src/api/api.ts
> +        return instance.get('/api/users/me')
все строки АПИ в константу, очень удобно брать их по ключу

2023-03-25 22:21 UTC, ValadzkoAliaksei commented on src/components/app/app.tsx
> +                    <Route path='books/:category/:bookId'
все строки роутов тоже в константу, так же как и АПИ

2023-03-25 22:21 UTC, ValadzkoAliaksei commented on src/components/header/header.jsx
> +                    }
подумай что бы была 1 модалка на весь проект, вдруг получится)

2023-03-25 22:21 UTC, ValadzkoAliaksei commented on src/components/utils/success-modal/success-modal.tsx
> +        dispatch(EditCommentSuccessAC(false))
че ж так много диспатчей то?

2023-03-25 22:21 UTC, ValadzkoAliaksei commented on src/pages/profile/book-list/book-list.tsx
> +        }
все эти расчеты дней можно делать в утилитках отдельно от компонентов?

2023-03-25 22:21 UTC, ValadzkoAliaksei commented on src/pages/profile/books-slider/books-slider.tsx
> +export const BooksSlider = (props: BooksSliderPT) => {
деструктуризируй пропсы!

2023-03-25 22:21 UTC, ValadzkoAliaksei commented on src/pages/profile/books-slider/books-slider.tsx
> +    }  else spaceBetween = 30
у слайдера есть breakpoints св-во

2023-03-25 22:21 UTC, ValadzkoAliaksei commented on src/pages/profile/books-slider/books-slider.tsx
> +                }}
а вот и оно... тогда эта манипуляция с window выглядит как лишняя

2023-03-25 22:21 UTC, ValadzkoAliaksei commented on src/pages/profile/profile.tsx
> +        }
это можно вынести в утилитку и переиспользовать

2023-03-25 22:21 UTC, ValadzkoAliaksei commented on src/pages/profile/profile.tsx
> +
манипуляции с Формдатой лучше делать перед самим запросом, а не в компоненте.
и вообще в компонентах должно быть как можно меньше логики, чисто отображение данных

2023-03-25 22:21 UTC, ValadzkoAliaksei commented on src/pages/profile/user-info/user-info.tsx
> +    const [valuePhone, setValuePhone] = useState<string>('');
не нужен дженерик с типом, если есть значение по умолчанию. тип выводится автоматом исходя из него

2023-03-25 22:21 UTC, ValadzkoAliaksei commented on src/pages/profile/user-info/user-info.tsx
> +}
очень большой и сложный компонент, можно лит его разбить? или вынести часть логики  в кастомный инпкут? подумай над этим. Если получится, то супер.

2023-03-25 22:21 UTC, ValadzkoAliaksei commented on src/selectors/selectors.ts
> +
можно обойтись 1 селектором, который просто берет profileData. А потом деструктуризирует его в компонентах, так как там нужно

2023-03-25 22:21 UTC, ValadzkoAliaksei commented on src/store/auth-reducer.ts
> +type UserInfoT = {
убери это T в конце плз

2023-03-25 22:21 UTC, ValadzkoAliaksei commented on src/store/book-reducer.ts
>  export const GetBookInfoTC = (id: number) => async (dispatch: AppDispatch) => {
может давай вынесем запросы от редюсера?

2023-03-26 06:32 UTC, SergeyGlazun requested changes

2023-03-26 06:32 UTC, SergeyGlazun commented on cypress.config.ts
>          screenshotsFolder: "cypress/report/screenshots",
![image](https://user-images.githubusercontent.com/70904466/227759251-9b15c01e-b3d2-4ece-830f-1ec125c0a636.png)
не закрывается выпадашка в не области и странная тень

2023-03-26 06:32 UTC, SergeyGlazun commented on cypress.config.ts
>          reporter: "mochawesome",
если поля не заполненны то летит запрос 
![image](https://user-images.githubusercontent.com/70904466/227759407-9b3ecf6b-7ab8-4a73-82ae-0c4c03456b9a.png)
в авторизации

2023-03-26 06:32 UTC, SergeyGlazun commented on cypress.config.ts
> +        experimentalSessionAndOrigin: true,
![image](https://user-images.githubusercontent.com/70904466/227759451-663764bc-e806-4eed-ad58-3f8446673cde.png)
когда изменяю пароль то уведомление о том что поле пустое появляется на секунду а  потом пропадает

2023-03-26 18:56 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 93%.
Общее количество тестов: 98.
Количество непройденных тестов: 6.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/9-app%20-burger-menu-close-768px.png)
***
**Sprint 5 -- authorization and registartion -- authorization -- success authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20success%20authorization%20(failed).png)
***
**Sprint 6 -- booking and book rate -- booking edit modal -- check cancel booking success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/Sprint%206%20--%20booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20cancel%20booking%20success%20(failed).png)
***
**Sprint 6 -- booking and book rate -- booking edit modal -- check edit booking request success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/Sprint%206%20--%20booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20edit%20booking%20request%20success%20(failed).png)
***
**Sprint 6 -- booking and book rate -- booking modal -- check booking request success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/Sprint%206%20--%20booking%20and%20book%20rate%20--%20booking%20modal%20--%20check%20booking%20request%20success%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- cancel-booking -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/Sprint%207%20--%20Profile%20functions%20tests%20--%20cancel-booking%20--%20success%20(failed).png)
***
**Sprint 7 -- profile page -- screenshots (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679857015/Sprint%207%20--%20profile%20page%20--%20screenshots%20(failed).png)

2023-03-26 23:45 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 97%.
Общее количество тестов: 98.
Количество непройденных тестов: 2.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/9-app%20-burger-menu-close-768px.png)
***
**Sprint 6 -- booking and book rate -- booking edit modal -- check cancel booking success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/Sprint%206%20--%20booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20cancel%20booking%20success%20(failed).png)
***
**Sprint 6 -- booking and book rate -- booking modal -- check booking request success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679874310/Sprint%206%20--%20booking%20and%20book%20rate%20--%20booking%20modal%20--%20check%20booking%20request%20success%20(failed).png)

2023-03-26 23:47 UTC, AndreyTverdovskiy commented
Кейс с "когда изменяю пароль то уведомление о том что поле пустое появляется на секунду а потом пропадает" воспроизвести не удалось. Локально все отображается.

2023-03-27 00:03 UTC, SergeyGlazun requested changes

2023-03-27 00:03 UTC, SergeyGlazun commented on src/components/app/app.tsx
>          if (bookingModal) {
![image](https://user-images.githubusercontent.com/70904466/227813190-fee8fe86-2684-45e7-ab3b-d7753df9b8ea.png)
при клике на логотип все куда-то пропадает и нет лодеров никаких

2023-03-27 00:57 UTC, SergeyGlazun commented on src/components/app/app.tsx
>      const [bookingId, setBookingId] = useState('')
это комент можешь пропустить посмотрел 5 спринт там не нужна была валидация

2023-03-27 00:58 UTC, SergeyGlazun commented
валидацию на авторизации можешь пропустить посмотрел 5 спринт там не нужна была она

2023-03-27 02:58 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 98.
Количество непройденных тестов: 0.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AndreyTverdovskiy/1679885882/9-app%20-burger-menu-close-768px.png)

2023-03-27 06:28 UTC, SergeyGlazun approved these changes

2023-03-27 09:17 UTC, ValadzkoAliaksei approved these changes

2023-03-27 09:18 UTC, merged